services:
  carla:
    image: carlasim/carla:0.9.13
    command: /bin/bash ./CarlaUE4.sh -quality-level=Low -RenderOffScreen
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority  
      - /dev/shm:/dev/shm:rw
